devel/php71-intl: Fix build
Starting with ICU 68 and laters, ICU no longer define TRUE and FALSE
macro for use with UBool, unless we define `U_DEFINE_FALSE_AND_TRUE=1` .

Ref: https://github.com/unicode-org/icu/commit/f6325d49ba57ec26f320b2865ce09ca47db458d9

Build log:

    In file included from /wrkdirs/overlays/php72/devel/php71-intl/work/php-7.1.33/ext/intl/collator/collator_sort.c:22:
    In file included from ./php_intl.h:23:
    In file included from /usr/local/include/php/main/php.h:35:
    In file included from /usr/local/include/php/Zend/zend.h:324:
    /usr/local/include/php/Zend/zend_operators.h:130:14: warning: implicit conversion from 'long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-const-int->
            } else if (!ZEND_DOUBLE_FITS_LONG(d)) {
                        ^~~~~~~~~~~~~~~~~~~~~~~~
    /usr/local/include/php/Zend/zend_operators.h:100:45: note: expanded from macro 'ZEND_DOUBLE_FITS_LONG'
    #       define ZEND_DOUBLE_FITS_LONG(d) (!((d) >= ZEND_LONG_MAX || (d) < ZEND_LONG_MIN))
                                                   ~~ ^~~~~~~~~~~~~
    /usr/local/include/php/Zend/zend_long.h:37:24: note: expanded from macro 'ZEND_LONG_MAX'
    # define ZEND_LONG_MAX INT64_MAX
                           ^~~~~~~~~
    /usr/include/x86/_stdint.h:90:19: note: expanded from macro 'INT64_MAX'
    #define INT64_MAX       0x7fffffffffffffff
                            ^~~~~~~~~~~~~~~~~~
    /wrkdirs/overlays/php72/devel/php71-intl/work/php-7.1.33/ext/intl/collator/collator_sort.c:349:26: error: use of undeclared identifier 'TRUE'
            collator_sort_internal( TRUE, INTERNAL_FUNCTION_PARAM_PASSTHRU );
                                    ^
    /wrkdirs/overlays/php72/devel/php71-intl/work/php-7.1.33/ext/intl/collator/collator_sort.c:543:26: error: use of undeclared identifier 'FALSE'
            collator_sort_internal( FALSE, INTERNAL_FUNCTION_PARAM_PASSTHRU );
                                    ^
    2 warnings and 2 errors generated.